# Generated by Django 5.0.3 on 2024-03-18 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0002_produit_logo_produit_pribarrer_produit_texte'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='nom_vendeur',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='prix_livraison',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
