# Generated by Django 5.0.3 on 2024-03-18 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='nom_vendeur',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
